### PR TITLE
Update animals table

### PR DESCRIPTION
**Pull request by emmiiorji**
This change perform updates on the animals table, adding more sample data alongside.

Here's a view of the updated sample data:

image

The following transactions occurred on the updated sample data (including screenshots of each result):

- Update species column of the animals table:

     image

- Delete animals table and roll back changes:
   
  image

- Delete animals born after Jan 1st, 2022 and modify negative weights to their absolute values:
     image

- Count number of animals in animals table:
     
image

- Get number of animals that have never tried to escape:
     
image

- Calculate average weight of animals:
     
image

- Determine whether neutered or non-neutered animals escape most:
image

- Get the maximum and minimum weight of each type of animal:

image

- Get the average number of escape attempts per animal type of those born between 1990 and 2000:

image

Thank you.

### CODE REVIEW

**Review by hiromataba — APPROVED** [review]
# Status: Approved :tada: :tada: :tada: 
Hi @emmiiorji    :wave: :wave: 

200w  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kingstalux** [comment]
Hi @emmiiorji, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :x: 

- [ ] You have submitted a project, that has already been approved and merged. Kindly create a new PR to submit for a review :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by sinansevgi — COMMENTED** [review]
Hello @emmiiorji 👋,

_This is an additional review as a result of the second opinion request._

Since your project was already approved the previous week and this is a solo project. I think your project can be approved again.

As this was the only reason that your project was not approved **it will be approved** as soon as possible.
Please ask for another review in your Dashboard and the **next Code Reviewer** will mark it as **approved** right away :)

Keep rocking 🚀!

**Review by thecodechaser — COMMENTED** [review]
## STATUS: APPROVED 🟢

## Hi @emmiiorji👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emmiiorji** [comment]
Thanks for the kind reviews.

**Pull request merged**
